apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  containers:
  - name: myapp
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    volumeMounts:
    - name: myvol
      mountPath: /root/.ssh

  volumes:
  - name:  myvol
    secret:
      secretName: pkey
